# Site settings
title: Good Clean Read
tag_text: Good Clean Read
description: A responsive template for publishing single-page websites, articles that are easy on the eyes
url: "http://vividalways.github.io"

# Build settings
markdown: kramdown

exclude: ["README.md"]
